# Generated by Django 3.0 on 2019-12-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amapp', '0003_auto_20191213_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='file_upload_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
